<a href="https://colab.research.google.com/github/juanflorezVe/COMP9058_lab1/blob/master/r00184264_juanflorez_assg1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
# Copying vervatim the code from the assignment
import tensorflow as tf
print(tf.__version__)
experiment = tf.Variable([1,2,3])
print(tf.divide(tf.reduce_sum(experiment),experiment.shape[0]))

2.4.1
tf.Tensor(2.0, shape=(), dtype=float64)


In [3]:
import tensorflow as tf
import numpy as np

from keras.utils import np_utils

fashion_mnist = tf.keras.datasets.fashion_mnist

# load the training and test data    
(tr_x, tr_y), (te_x, te_y) = fashion_mnist.load_data()

# reshape the feature data
tr_x = tr_x.reshape(tr_x.shape[0], 784)
te_x = te_x.reshape(te_x.shape[0], 784)

# noramlise feature data
tr_x = tr_x / 255.0
te_x = te_x / 255.0

print( "Shape of training features ", tr_x.shape)
print( "Shape of test features ", te_x.shape)


# one hot encode the training labels and get the transpose
tr_y = np_utils.to_categorical(tr_y,10)
tr_y = tr_y.T
print ("Shape of training labels ", tr_y.shape)

# one hot encode the test labels and get the transpose
te_y = np_utils.to_categorical(te_y,10)
te_y = te_y.T
print ("Shape of testing labels ", te_y.shape)

4423680/4422102 [==============================] - 0s 0us/step
Shape of training features  (60000, 784)
Shape of test features  (10000, 784)
Shape of training labels  (10, 60000)
Shape of testing labels  (10, 10000)


In [132]:
#Let's insert 784 parameters to each neuron
# A = W.T * X + b
# layer_pass will take the x matrix, pass it to the l layer applying the w weights and adding the b bias
#NeuralNetworksW5 slide 11
# m = 60000
# n = 784
# p = 200
def relu_layer_pass(w, x, b):
  t = tf.matmul(w,x)
  l = tf.add(t,b)
  h = tf.nn.relu(l)
  return h

def softmax_layer_pass(w, x, b):
  t = tf.matmul(w,x)
  l = tf.add(t,b)
  h = tf.nn.softmax(l)
  return h

def loss_function(predicted, expected, x=None):
  E = tf.math.subtract(predicted, expected)
  print(E.shape)
  db = tf.divide(tf.reduce_sum(E),E.shape[0])
  d_lambda = tf.divide((x * tf.transpose(E)), E.shape[0])
  return d_lambda

In [133]:
def forward_pass(w1, w2, b1, b2, x):
  #pass the first layer
  h1 = relu_layer_pass(w1,x,b1)
  #pass the second layer
  h2 = softmax_layer_pass(w2,h1,b2)
  return h2
  #print(H1.shape)
  #print(H2.shape)

In [134]:
# from lecture (VectorizedLogistiRegression, page 50) March 9th.... 
# We have a set of trainning of 60000 rows (instances)
# and 748 columns ( Features)
# Our X vector has 784 rows (as fetarues) and 60000 columns (instances)
X = tf.Variable(tr_x.T, dtype = tf.float32)
print("X shape is {}".format( X.shape))
# Let's create a vector W1 with the number of weights (784) for each neuron in one row
# so, it means 200 rows and 784 columns ( Features) for layer 1
W1 = tf.Variable(tf.random.normal([ 200,784], mean=0.0, stddev=0.05))
#The bias for the first layer of 200 neurons will be a vecoter of 200 rows (1 per neuron)
# and 1 column
B1 = tf.Variable(tf.random.uniform(shape=[200,1],dtype=tf.float32))


print ("W1 shape is{}".format(W1.shape))
print ("B1 shape is{}".format(B1.shape))

X shape is (784, 60000)
W1 shape is(200, 784)
B1 shape is(200, 1)


In [135]:
#The second layer:
# W2 has 10 rows (as it has 10 possible classes)
W2 = tf.Variable(tf.random.uniform(shape=[10,200], dtype=tf.float32, minval=-0.1, maxval=0.1))
B2 = tf.Variable(tf.random.uniform(shape=[10,1], dtype=tf.float32))
print ("W2 shape is{}".format(W2.shape))
print ("B2 shape is{}".format(B2.shape))

W2 shape is(10, 200)
B2 shape is(10, 1)


Question 1, section a. Question1_1_1


In [136]:
learning_rate=0.01
iterations=70
adam_optimizer=tf.keras.optimizers.Adam()


In [137]:
# Rgression loop
#for i in range(iterations):
#  with tf.GradientTape() as tape:
#    H = forward_pass(W1,W2,B1,B2,X)
#    current_loss = loss_function(H, tr_y) # 2 vectors witht the derivated to update W1 and W2
  
    

In [138]:
#Unit tests
xu = tf.Variable([[0.3,0.2,0.1],
                  [0.7,0.6,0.5],
                  [0.2,0.2,0.2]])
big = tf.Variable([6.0,8.0,10.0])
small = tf.Variable([5.0,7.0,9.0])
print(loss_function(big, small, xu)) # should be xu/3
print(loss_function(small, big, xu)) # should be -xu/3

(3,)
tf.Tensor(
[[0.1        0.06666667 0.03333334]
 [0.23333333 0.2        0.16666667]
 [0.06666667 0.06666667 0.06666667]], shape=(3, 3), dtype=float32)
(3,)
tf.Tensor(
[[-0.1        -0.06666667 -0.03333334]
 [-0.23333333 -0.2        -0.16666667]
 [-0.06666667 -0.06666667 -0.06666667]], shape=(3, 3), dtype=float32)
